### ISSUE TITLE
DeprecationWarning: Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format 

### ISSUE THREAD

**Issue by monbro** [3Top/word2vec-api#23]
Being on `gensim-3.2.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl` I get this error.
````
Traceback (most recent call last):
  File "word2vec-api.py", line 121, in <module>
    model = w.load_word2vec_format(model_path, binary=binary)
  File "/Library/Python/2.7/site-packages/gensim/utils.py", line 1302, in new_func1
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 1608, in load_word2vec_format
    raise DeprecationWarning("Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.")
DeprecationWarning: Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.
````

I had to change the `word2vec-api.py` file and insert:
`from gensim.models.word2vec import KeyedVectors as wk`

and to change `model = w.load_word2vec_format(model_path, binary=binary)`to `model = wk.load_word2vec_format(model_path, binary=binary)` then it worked.

**Comment by monbro** [comment]
Ok the cause for this was, that I had for some reason to uninstall gensim and reinstall it while it used the latest version then. Which resulted in the above shown error.
